"""Build the modelling feature matrix from synthetic input tables."""
from __future__ import annotations

try:
    from src.config import DATA_DIR, OUTPUT_DIR, ensure_project_directories
except ModuleNotFoundError:
    from config import DATA_DIR, OUTPUT_DIR, ensure_project_directories  # type: ignore

import pandas as pd


def load_synthetic_tables() -> dict[str, pd.DataFrame]:
    """Load synthetic input tables generated by src/data_generation.py."""
    tables = {
        "customers": pd.read_csv(DATA_DIR / "customers.csv"),
        "monthly_behaviour": pd.read_csv(DATA_DIR / "monthly_behaviour.csv", parse_dates=["snapshot_month"]),
        "credit_products": pd.read_csv(DATA_DIR / "credit_products.csv"),
        "credit_outcomes": pd.read_csv(DATA_DIR / "credit_outcomes.csv", parse_dates=["snapshot_month"]),
        "treatment_log_sample": pd.read_csv(DATA_DIR / "treatment_log_sample.csv", parse_dates=["recommendation_month"]),
    }
    return tables


def build_feature_matrix() -> pd.DataFrame:
    """Create a customer-month modelling table with anti-leakage-safe features."""
    ensure_project_directories()
    tables = load_synthetic_tables()
    customers = tables["customers"]
    behaviour = tables["monthly_behaviour"]
    outcomes = tables["credit_outcomes"]

    df = behaviour.merge(customers, on="customer_id", how="left", validate="many_to_one")
    df = df.merge(outcomes, on=["customer_id", "snapshot_month"], how="left", validate="one_to_one")

    df["balance_to_income_ratio"] = df["savings_balance"] / (df["annual_income"] + 1)
    df["credit_to_income_ratio"] = df["credit_balance"] / (df["annual_income"] + 1)
    df["product_depth_score"] = (df["number_of_products"].clip(1, 8) / 8).round(4)
    df["affordability_proxy"] = (
        (df["annual_income"] / 12) / (df["credit_balance"] + 250)
    ).clip(0, 20)

    # Keep the model-ready view compact and explicit.
    ordered_cols = [
        "customer_id",
        "snapshot_month",
        "age",
        "income_band",
        "income_band_score",
        "annual_income",
        "employment_type",
        "region",
        "tenure_months",
        "customer_segment",
        "digital_engagement_score",
        "savings_balance",
        "credit_balance",
        "number_of_products",
        "recent_balance_growth",
        "recent_credit_enquiry_flag",
        "salary_inflow_flag",
        "engagement_score",
        "utilisation_ratio",
        "arrears_last_6m",
        "balance_to_income_ratio",
        "credit_to_income_ratio",
        "product_depth_score",
        "affordability_proxy",
        "converted_next_3m",
        "responsible_credit_behaviour_6m",
        "observed_product_id",
    ]
    df = df[ordered_cols].sort_values(["snapshot_month", "customer_id"]).reset_index(drop=True)
    df.to_csv(OUTPUT_DIR / "feature_matrix.csv", index=False)
    return df


if __name__ == "__main__":
    features = build_feature_matrix()
    print(f"Built feature matrix: {features.shape[0]:,} rows x {features.shape[1]:,} columns")
